import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/shared/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tindi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: { colorPrimary: "#fb7185" },
        signIn: {
          variables: { colorPrimary: "#fb7185" },
        },
      }}
      afterSignInUrl="/explore"
      afterSignUpUrl="/onBoard"
    >
      <html lang="en">
        <body className={quicksand.className}>
          <Navbar />
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
